name: Run Mojo tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      RUNNER_ALLOW_RUNASROOT=1 ./config.sh --token asdlkjfasdlkj

    steps:
    - uses: actions/checkout@v2

    - name: Keep sudo
      run: sudo -s

    - name: Install modular
      run: |
        sudo apt-get install -y apt-transport-https &&
        keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
        sudo curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
        sudo curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
        sudo apt-get update &&
        sudo apt-get install -y modular

    - name: Install Mojo
      run: |
        modular auth ${{ secrets.AUTH_TOKEN }} &&
        modular install mojo

    - name: Run tests
      run: mojo tests.mojo
