name: Run Mojo tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install modular
      run: |
        curl https://get.modular.com | \
        MODULAR_AUTH=${{ secrets.AUTH_TOKEN }} \
        sh -

    - name: Add to PATH
      run: |
        echo 'export MODULAR_HOME="/home/runner/.modular"' >> $GITHUB_ENV
        echo 'export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"' >> $GITHUB_ENV

    - name: Set Environment Variables
      run: echo "source $GITHUB_ENV" >> $HOME/.bashrc

    - name: Run tests
      run: mojo tests.mojo
