name: Run Mojo tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install modular
      run: |
        keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
        curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
        echo 'deb [signed-by=${keyring_location}] https://dl.modular.com/bBNWiLZX5igwHXeu/installer/deb/debian stable main' | sudo tee /etc/apt/sources.list.d/modular-installer.list &&
        sudo apt-get update &&
        sudo apt-get install -y modular

    - name: Install Mojo
      run: |
        modular auth ${{ secrets.AUTH_TOKEN }} &&
        modular install mojo

    - name: Run tests
      run: mojo tests.mojo
