name: Run Mojo tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install modular
      run: |
        curl https://get.modular.com | \
        MODULAR_AUTH=${{ secrets.AUTH_TOKEN }} \
        sh -


    - name: Install Mojo
      run: |
        modular install mojo

    - name: Add to PATH
      run: |
        # $GITHUB_PATH
        # echo 'export MODULAR_HOME="/home/runner/.modular"' >> $GITHUB_PATH
        # echo 'export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> $GITHUB_PATH
        echo 'MODULAR_HOME="/home/runner/.modular"' >> $GITHUB_PATH
        echo 'PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> $GITHUB_PATH
        # echo 'export MODULAR_HOME="/home/runner/.modular"' >> ~/.bashrc
        # echo 'export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc
        # source ~/.bashrc
        # echo 'export MODULAR_HOME="/home/runner/.modular"' >> ~/.zshrc
        # echo 'export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
        # source ~/.zshrc

    - name: Run tests
      run: mojo tests.mojo
